# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accountCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('accountName', models.CharField(max_length=200)),
                ('accountTypeCode', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOper', models.DateField()),
                ('nameOper', models.CharField(max_length=200)),
                ('sumOper', models.DecimalField(decimal_places=2, max_digits=20)),
                ('accDtOper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_dt', to='homeaccounting.Accounts')),
                ('accKtOper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_kt', to='homeaccounting.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Orginfo',
            fields=[
                ('orgId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('orgName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='operations',
            name='orgOper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeaccounting.Orginfo'),
        ),
    ]
