# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeaccounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsOrg',
            fields=[
                ('accountCode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('accSegAnalit', models.CharField(max_length=2)),
                ('accountName', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='operations',
            old_name='orgOper',
            new_name='org',
        ),
        migrations.AddField(
            model_name='accounts',
            name='accountSegment1',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='accountSegment2',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operations',
            name='accDtOper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_dt', to='homeaccounting.AccountsOrg'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='accKtOper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_kt', to='homeaccounting.AccountsOrg'),
        ),
        migrations.AddField(
            model_name='accountsorg',
            name='accountBaseCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeaccounting.Accounts'),
        ),
        migrations.AddField(
            model_name='accountsorg',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeaccounting.Orginfo'),
        ),
    ]
